Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: 
        Name: !Ref EC2InstanceProfile # Updated to use !Ref instead of !GetAtt for instance profile name
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1f0 # Example for Amazon Linux 2
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      InstanceMarketOptions: # Spot instance logic
        Fn::If:
          - IsSpotEnvironment
          - MarketType: spot
          - !Ref "AWS::NoValue" # If production, no spot instance options
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-OpenSupports-EC2"

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP and SSH access"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 203.0.113.0/24 # Restrict SSH access to a known IP range (update this as needed)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: # Outbound traffic rules
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0 # Allow all outbound traffic
