Resources:
  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-application-bucket
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
Outputs:
  S3BucketPrefix:
    Description: "S3 bucket prefix based on environment"
    Value: !Sub "my-application-bucket/${EnvironmentName}/"
