Resources:
  OpenSupportsPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::<account-id>:role/CodePipelineServiceRole
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: <github-owner>
                Repo: <github-repo>
                Branch: main
                OAuthToken: <GitHub-Token>
        - Name: DeployToDevelopment
          Actions:
            - Name: DeployDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: OpenSupports-dev
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceOutput::main.yaml
                ParameterOverrides: |
                  {"EnvironmentName":"dev","InstanceType":"t2.micro","DBName":"OpenSupportsDBDev","DBUser":"admin","DBPassword":"mydevpassword"}
        - Name: ApprovalForStaging
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
        - Name: DeployToStaging
          Actions:
            - Name: DeployStaging
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: OpenSupports-staging
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceOutput::main.yaml
                ParameterOverrides: |
                  {"EnvironmentName":"staging","InstanceType":"t3.micro","DBName":"OpenSupportsDBStaging","DBUser":"admin","DBPassword":"mystagingpassword"}
        - Name: ApprovalForProduction
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
        - Name: DeployToProduction
          Actions:
            - Name: DeployProduction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: OpenSupports-prod
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: SourceOutput::main.yaml
                ParameterOverrides: |
                  {"EnvironmentName":"prod","InstanceType":"t3.medium","DBName":"OpenSupportsDBProd","DBUser":"admin","DBPassword":"myprodpassword"}
